{
 "title": "solardigi",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "U/I", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Voltages",
   "type": "timeseries",
   "description": "Voltages",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expression": "($A * 0.01) + 2.5", "type": "math" },
    { "expression": "($C * 0.01) + 2.5", "type": "math" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "description": "Battery Voltage",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A * 0.01) + 2.5", "type": "math" }
   ]
  },
  {
   "title": "Solar Voltage",
   "type": "gauge",
   "description": "Solar Voltage",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A * 0.01) + 2.5", "type": "math" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Temperature",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A * 0.16016) - 40", "type": "math" }
   ]
  },
  {
   "title": "Packets Digipeated",
   "type": "stat",
   "description": "Packets Digipeated",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  count(digipeated) AS \"digipeated\"\nFROM packet\nWHERE\n  $__timeFilter(datetime) and\n  digipeated > 0\n"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "bargauge",
   "description": "Battery Current",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A*1.25)-500", "type": "math" }
   ]
  },
  {
   "title": "Sunshine",
   "type": "stat",
   "description": "U Solar > 4.3V",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$C * 10", "type": "math" }
   ]
  },
  {
   "title": "Solar Current",
   "type": "bargauge",
   "description": "Solar Current",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "(($A*1.25)-500) * -1", "type": "math" }
   ]
  },
  {
   "title": "Battery budget",
   "type": "stat",
   "description": "Messwert * 60 * 10 (mAs).\nSumme aller Messwerte / 60 / 60 (mAh)",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$sumVal / 60.0 / 60.0", "type": "math" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "description": "Current",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    { "expression": "($A*1.25)-500", "type": "math" },
    { "expression": "(($B*1.25)-500) * -1", "type": "math" }
   ]
  },
  {
   "title": "Last Packet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  id\nFROM telemetry\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Last Telemetry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  id\nFROM telemetry\nWHERE\n  $__timeFilter(datetime) AND\n  callsign = 'DJ1AN-1'\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  raw AS \"Packet\"\nFROM packet\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime DESC"
    }
   ]
  }
 ]
}